#!/usr/bin/env python
"""Craft Command.

Run "python craft" to see every command available in your application,
and "python craft <command> --help" for details on a specific command.
"""

from wsgi import application

if __name__ == "__main__":
    application.make("commands").run()
