from typing import Any, Callable, Union

from ..http import HTTPResponse, PendingRequest

class Http:
    def with_headers(headers: dict) -> PendingRequest: ...
    def with_token(token: str, prefix: str = "Bearer") -> PendingRequest: ...
    def with_basic_auth(username: str, password: str) -> PendingRequest: ...
    def timeout(seconds: int) -> PendingRequest: ...
    def retry(times: int, sleep: int = 0) -> PendingRequest: ...
    def get(url: str, query: dict = None) -> HTTPResponse: ...
    def post(url: str, data: dict = None, json: dict = None) -> HTTPResponse: ...
    def put(url: str, data: dict = None, json: dict = None) -> HTTPResponse: ...
    def patch(url: str, data: dict = None, json: dict = None) -> HTTPResponse: ...
    def delete(url: str, data: dict = None, json: dict = None) -> HTTPResponse: ...
    @staticmethod
    def response(
        body: Any = b"", status: int = 200, headers: dict = None
    ) -> HTTPResponse: ...
    def fake(stubs: dict = None) -> "Http": ...
    def stop_faking() -> "Http": ...
    def is_faking() -> bool: ...
    def recorded() -> list: ...
    def assert_sent(url: str) -> None: ...
    def assert_sent_count(count: int) -> None: ...
    def assert_nothing_sent() -> None: ...
